openapi: 3.0.1
info:
  title: Employee V1
  version: 0.1.0
servers:
- url: "{server}:{port}/employee/v1"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /employees:
    get:
      operationId: getEmployees
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeList'
  /employees/{empID}:
    get:
      operationId: getEmployeesEmpid
      parameters:
      - name: empID
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        "404":
          description: NotFound
  /employee:
    post:
      operationId: postEmployee
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        "400":
          description: BadRequest
components:
  schemas:
    Employee:
      required:
      - address
      - id
      - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        address:
          type: string
    EmployeeList:
      required:
      - count
      - employees
      type: object
      properties:
        count:
          type: integer
          format: int64
        employees:
          type: array
          items:
            $ref: '#/components/schemas/Employee'
